development:
adapter: postgresql
database: beakrr_development
pool: 5
timeout: 5000
test:
adapter: postgresql
database: beakrr_test
pool: 5
timeout: 5000

production:
adapter: postgresql
database: beakrr_production
pool: 5
timeout: 5000